name: Build Fabric Mod

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.10.2

      - name: Build jar
        run: gradle build

      - name: Upload mod
        uses: actions/upload-artifact@v4
        with:
          name: ChatTabs-v3
          path: build/libs/*.jar
